"""Added required tables

Revision ID: 3978d6924ed8
Revises: 26fcfdfca49b
Create Date: 2022-05-30 12:57:03.549147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3978d6924ed8'
down_revision = '26fcfdfca49b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=40), nullable=True))
    op.drop_index('ix_users_emai', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'emai')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('emai', sa.VARCHAR(length=40), nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_emai', 'users', ['emai'], unique=False)
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
